stages:
  - build

build:
  stage: build
  tags:
    - generic
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - cp ${PERSONAL_DOCKERHUB_CONFIG} /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
      --destination "${CI_PROJECT_NAME}:latest"
